### ISSUE TITLE
Point cloud library and opencv

### ISSUE THREAD

**Issue by vigneshDurai14** [noshluk2/ros1_wiki#13]
can you please make a video for converting (RGB + depth image) to a 3D point cloud? mathematical explanation...

**Comment by noshluk2** [comment]
- Check Rtab Mapping for ROS2 using Depth Images -> [3D Point Cloud Mapping ](https://youtu.be/VCobOzw2kHM)
- then process this 3D point cloud using pcl -> [C++ PCL processing ](https://youtu.be/rcCsN_JSHoQ)
