### ISSUE TITLE
ROS turtle mover/formation

### ISSUE THREAD

**Issue by engrvinzz** [noshluk2/ros1_wiki#14]
Please provide an in sight to this for solving this.

Using a launch file to spawn 3 turtles, namely leader, followerA and followerB, in
the turtlesim simulator
• The leader turtle is located in the center with no rotation. The other 2 followers start at a
random position and orientation.
• Define a custom message namely YourBCodeLeaderMessage.msg as shown below
used to send an instruction from the leader to two followers
Fig. 1 The YourBcodeLeaderMessage.msg message to be defined
• The leader starts with sending an instruction using the defined message to two followers asking
them to move to the formation position, i.e. followerA is 1 meter behind the leader and
followerB is 1 meter behind followerA as illustrated in
• Once the leader detects that the two followers are in the required formation position, it turns
to a random direction and then keep moving in a straight line with a red pen until it reaches
the boundary of the turtlesim window. The three turtles should maintain column formation
while moving, i.e. three turtles travel one after the other with two
followers move with a white pen.
Hints: The formation control could be easily achieved by publishing additional frames to the
leader turtle. Here is the tutorial you might find helpful.
. An illustration of leader-follower formation. i.e. followerA is 1 meter behind the leader and
followerB is 1 meter behind the followerA
• Defining a custom ROS service, namely YourBcodeServicePID.srv, which provides a
service allowing a given turtle moves to a specified location using a PID controller as illustrated
in Fig. 3.
Hints: Here is a link which you can find how to use a PID controller to move a robot to a specific
location
• When the leader turtle approaches to the border, it will send another instruction (again using
the defined message) to the followers and do the following
o Teleport 2 followers to their initial position through the service (i.e.
turtlesim/TeleportAbsolute) provided by ROS
o The leader turtle returns to the center through the custom service defined above (i.e.
YourBcodeServicePID.srv). If the PID server fails to move the turtle to the goal
location, the leader turtle should be teleported back to the center
o All the turtles should return to their initial position with a black pen
• A Vodcast is required to be produced to accompany your implementation within which a brief
walkthrough demonstration of your implementation and a walkthrough of the underlying
source code, along with an associated commentary.
2. Marking scheme
• Using a launch file to spawn 3 turtles at required positions
• Creating a custom ROS message, i.e. LeaderMessage.msg and a custom
ROS service, i.e. ServicePID.srv
• Communication between the leader and follower turtles using the defined message
• The leader turtle moves in a random direction
• The control of leader-follower formation
• Turtles return to their initial position

**Comment by noshluk2** [comment]
## General Outline : 
### Define Files 
- YourBCodeLeaderMessage.msg message file
	- This node should handle the formation control, ensuring that the followers stay in the desired position relative to the leader.This node should handle the formation control, ensuring that the followers stay in the desired position relative to the leader.
- YourBcodeServicePID.srv service file
	- This service to move the leader turtle to the desired location. This node should use a PID controller to move the turtle in a straight line until it reaches the boundary of the turtlesim window.
- Launch File to spawn all and sets their initial positions and orientations, and starts the leader and follower nodes.
	- When the leader turtle approaches the border, it should send a message to the followers instructing them to return to their initial positions using the turtlesim/TeleportAbsolute service, and then return to the center using the YourBcodeServicePID service.

**Comment by engrvinzz** [comment]
Can you please provide python code solution for this?

**Comment by engrvinzz** [comment]
Hi Mohammed,

Could you please proffer a python code solution to this issue?

Thanks.
